# Generated by Django 4.2 on 2023-04-05 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_name_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desc',
            new_name='user_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phonenumber',
        ),
    ]
