# Generated by Django 4.2 on 2023-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_desc_profile_user_bio_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_bio',
            field=models.TextField(default='', max_length=500),
        ),
    ]
