# Generated by Django 4.2 on 2023-04-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_bio_profile_bio_profile_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_updated',
            new_name='date_modified',
        ),
    ]
