# Generated by Django 4.2 on 2023-04-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_last_updated_profile_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_modified',
            new_name='last_updated',
        ),
    ]
