# Generated by Django 4.2 on 2023-04-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_users_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='synopsis',
            field=models.CharField(default='Place holder', max_length=100),
        ),
    ]
