# Generated by Django 4.2 on 2023-04-18 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_post_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='..\\static\x07ssets\\img\\profile\\default-profile-photo.jpg', upload_to='user/avatar'),
        ),
    ]
